/* Cable: CMake Bootstrap Library.
 * Copyright 2019 Pawel Bylica.
 * Licensed under the Apache License, Version 2.0.
 */

/* Generated by Cable Build Info on @TIMESTAMP@. Do not modify directly. */

#pragma once

#define ALETH_VERSION "@PROJECT_VERSION@"

#ifdef __cplusplus
constexpr auto aleth_version = "@PROJECT_VERSION@";
#endif
